name: music_player_app
description: A basic music player app with background play feature.

# Other project information...

dependencies:
  flutter:
    sdk: flutter

  # YouTube Player Flutter package
  youtube_player_flutter: ^9.0.3
  audioplayers: ^6.0.0
  shared_preferences: ^2.0.13
  # Flutter Background package
  flutter_background: ^1.3.0+1
  flutter_lints: ^4.0.0
  http: ^1.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: '^3.5.0'
# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  